In [1]:
import re
import tgt
import os
import pandas as pd

In [119]:
def cleanup(path):
    allchars = set()
    file = open(path)
    file = file.read()
    for word in file:
        allchars.update(char.lower() for char in word) #посмотрим символы до очистки: оставляем знаки препинания, чтобы поправить паузы вручную
    print(sorted(allchars), sep='')
    file = file.lower().replace('\n', ' ') #склеим текст
    file = re.sub('\s+', ' ', file).strip()
    file = file.replace('ÿ', 'ӈ') #правим кодировку
    file = file.replace('џ', 'ӈ')
    file = file.replace('¸', 'ё')
    file = file.replace('¨', 'ё')
    file = file.replace('& ', '') #убираем переносы
    file = file.replace('&', '-')
    start, end = file.find('1й пеляда'), file.find('вади” хамэди”') #откидываем вступление и словарь
    file = file[start:end]
    versepat = r'(\d+й\sпеляда)'
    file = re.sub(versepat, r'\n___\1___\n', file)
    file = re.sub(r'\*+\s\d+:\d+[а-я\s’,«»”.ӈ]+', '', file) #убираем сноски
    file = re.sub(r'(марк|иоанн)\s\d+(,\s\d+)?', '', file) #убираем названия страниц в начале
    splitpat = r'([.!?:])\s*' #делим по строкам так, где скорее всего будут паузы
    file = re.sub(splitpat, r'\1\n', file)
    file = re.sub('\d+\s', '', file) #чистим от чисел
    newchars = set() #посмотрим на символы после очистки:
    for word in file:
        newchars.update(char.lower() for char in word)
    print(sorted(newchars), sep='')
    newname = path.replace('.txt', '_new.txt')
    with open(newname, 'w') as ffile:
        ffile.write(file)
    print(f'Создан файл {newname}')

In [100]:
cleanup('/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/yrk_cyrillic_Mark.txt')

['\n', ' ', '!', '&', "'", '(', ')', '*', ',', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', '@', '[', ']', '_', 'a', 'b', 'e', 'f', 'g', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', '¨', '©', '«', '¸', '¹', '»', '×', 'ÿ', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'џ', '–', '’', '”', '‹', '›']
['\n', ' ', '!', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', '[', ']', '_', '«', '»', 'а', 'б', 'в', 'г', 'д', 'е', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'ӈ', '–', '’', '”', '‹', '›']
Создан файл /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/yrk_cyrillic_Mark_new.txt

In [107]:
#у иоанна и рассказов другое оформление, поэтому функция выше не подходит
path = '/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Gospel parables.txt'
parables = open(path)
parables = parables.read()
parables = parables.lower().replace('\n', ' ')
start, end = parables.find('палестинахана иудей”'), parables.find('19')
parables = parables[start:end]
parables = parables.replace('- ', '')
seppat = r'(\(.*?\))'
parables = re.sub(seppat, r'\n___\1___\n', parables)
parables = re.sub(seppat, '', parables) #чистим от скобок
parables = re.sub(r'\d+', '', parables) #чистим от чисел
splitpat = r'([.!?:])\s*'
parables = re.sub(splitpat, r'\1\n', parables)
newname = path.replace('.txt', '_new.txt')
with open(newname, 'w') as ffile: #сохраняем в новый файл
    ffile.write(parables)

In [ ]:
print(parables[:1000], sep='\n') #что получилось после чистки и деления

палестинахана иудей” пунрёбцо’ мэсымана илени” ерв” тикы мэсымана ниня ӈэди”, хэбяхасавэй ненэцие” поӈгана мэна иисусм’ судебавэдо’.
вомдартаӈгода вадидо’ пуня’ пэраць, иисус хара явна ӈэда лахарём’ вадець пя.
тикы лахарё сидя хасава нясха’, тика нисянди’ нямна ӈа.
тикы хара явна ӈэда лахарёхона нисяди’ нум’ пыдикабт”, нюдяюм’ хасава нюда – иланда сехэрым’ ё”мы хэбяхасавэй, ӈаркаюмгав, хэбяхасавэй судебада иудей” пунрабцо’ мэсымана илени” то”лаха”.
ёховы хасава ню’ нямна ӈэда лахарё
______
  иисус тамна тяха’ лахана:
«ӈоб” ненэць’ сидя ню да ӈэвы.
нюдяюм’ нисяханда ма”нив’:
‹нисёв!
е”ни толёда илебцанд пелям’ тад›.
тиканда нисяда илебцамда нюхуюта помна тярӈада.
мале сян’ яля’ хэ”мяхад нюдя нюда ӈавэда мал’ ханахая, хубта ян’ хая, таняна иламда са”лимдемба харта илебцамда сад”ӈада.
ӈаворида мал’ садсо”махаданда, тикы я’ тиӈгэвна ӈарка сэрад” то, тиканда пыда маӈгбалъй”.
тиканда, таняӈы яхана иленя ӈоб” ненэцянд’ хая, илелъй”.
тикы ненэць’ парась’ пэртяӈэ парасиета хадылава ян’ ӈэдарад

In [ ]:
path = '/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John.txt'
john = open(path)
john = john.read()
john = john.lower().replace('\n', ' ')
start, end = john.find('1‑й пеляда'), john.find('вади” хамэди”') #откидываем вступление и словарь
john = john[start:end]
john = john.replace('- ', '')
versepat = r'(\d+‑й\sпеляда)'
john = re.sub(versepat, r'\n___\1___\n', john)
john = re.sub(r'\*+\s\d+:\d+[а-я\s’,«»”.–ӈ]+', '', john) #убираем сноски
john = re.sub(r'(марк|иоанн)\s\d+(,\s\d+)?', '', john) #убираем названия страниц в начале
john = re.sub(r'\(.*?\)', '', john) #чистим от скобок
john = re.sub(r'\d+ ', '', john) #чистим от чисел
john = john.replace('*', '')
john = re.sub(splitpat, r'\1\n', john)
newname = path.replace('.txt', '_new.txt')
with open(newname, 'w') as ffile: #сохраняем в новый файл
    ffile.write(john)

In [103]:
print(john[:1000], sep='\n')

___1‑й пеляда___
 вада ненэцяӈэ хэ”мя сямянхат ӈули” нюрте” э’ вада танявы, вада нумгана мэвы, пыда нум’ ӈэвы.
вада нюрте” эхэд нумгана мэвы.
хусувэй ӈамгэ няданда ӈадимы.
хусувэй ӈадимы ӈамгэ пыдасиципой” ӈадимзь нивэда пирас”.
вадахана ил’ танявы, тикы ил’ ненэцие” яляӈэ таравы.
тикы яля пэвдяхартахана ялэмды, пэвдя сита пирда” ле ни пирас”.
нум’ ӈэдаравы ӈопой хасава танявы, нюмда иоанн ӈэвы.
пыда яля’ нямна ненэсям’ ваде” манзь товы.
тиканда хусувэй хибя сита намд” махаданда ялян’ пунраӈгу” ни” им’.
пыдахавада яля нивы ӈа”, хуркавна ӈо” пыда яля’ нямна ненэсям’ ваде” манзь нум’ ӈэдаравэда.
яляхав, ненэся яляхав, хусувэй ненэцям’ ялэмдамбада, мале та’ мальӈгана я’ тир’ ни’ ӈадимдавы.
пыда я’ тиркана танявы, я’ тир” няданда ӈадимы ӈэбта ӈод”, я’ тир’ тер” сита ни” хамэда”.
пыда харта  ӈамгэхэта то.
харта ненэциеда сита сейхато’ ня”маван’ ни” харва”.
сита сейхато’ ня”амвэхэв” нянда пунрэяд”.
тикы ненэцяӈг” пыда нум’ ню” ӈэсь ватодамдо’ ми”ӈа.
пыдо’ ненэця’ паӈгхад, пыхыд’ харвабцоход

In [96]:
path = '/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah.txt'
jonah = open(path)
jonah = jonah.read()
jonah = jonah.lower().replace('\n', ' ')
jonah = jonah.replace('- ', '')
startpat = r'(\d\s\d)' #делим на части
jonah = re.sub(startpat, r'\n___\1___\n', jonah)
jonah = re.sub(r'\d+', '', jonah) #чистим от чисел
splitpat = r'([.!?:])\s*'
jonah = re.sub(splitpat, r'\1\n', jonah)
newname = path.replace('.txt', '_new.txt')
with open(newname, 'w') as ffile: #сохраняем в новый файл
    ffile.write(jonah)

In [102]:
print(jonah[:1000], sep='\n')

иона’ нум’ ерв’ сякад хуноро”ма
___ ___
 амиттай’ хасава нюн’, ионан’ нум’ ерв вадам’ мэ”мы:
«юркад, сюдбя март’, ниневиян’ хань”.
нум’ вато’ вадес”, мань няни вэва серото’ юн тэвыць ».
иона юркы”, нум’ ерв’ сякад таршишан’ хунаванзь иоппиян’ то.
таняна таршишан’ миндя ӈарка” я ӈаном’ хо, мирта салда, тадтикахад ӈанон’ тий”.
нум’ ерв’ сякад хуна, ненэцие” поӈгана таршиш’ няю’ нэкалӈада.
ӈопой, нум’ ерв ямд’ сата мерцям’ ӈэдара, тикахавахад сюдбя хамба” ӈадибелыд”.
ӈано тахараван’ харва.
ӈанохона манзарана” сейдо’ хая”.
хусувэдо’ харта хэхэхэнда ханорць тёры”ӈа.
ӈаномдо’ сибимдемба пэндъидо’ ямд’ моёядо’.
ионахав ӈано’ мю’ таси’ пакалъй”, юсибтэй”, ӈамгэхэртахат ехэра хонарэй”.
ӈано’ ӈэвахана мэна някунда то, ма:
«ӈамгэ пыдар хонын?
!
юркад”, харт нумганд туёс”!
маси”, пыда сидна” тензибтеӈгу, маня” вэ’ нива” ханд”».
мал’ няхато’ лахана пэяд”:
«ти, серебям’ мохова”!
хибяна” е”эмня маянд’ еремява”, манэкава” ».
серебям’ мо”, серебя ионан’ ха”мы”.
тиканда няби” хонрамба пядо’:
«маӈгар”,

In [5]:
def split_text_into_verses(txt_path):
    with open(txt_path, 'r', encoding='utf-8') as f:
        text = f.read()
    verses = {}
    current_verse = None
    for line in text.split('\n'):
        line = line.strip()
        if line.startswith('___') and line.endswith('___'): #ищем начало
            verse_num = line[3:-3].split('й пеляда')[0].strip().replace('‑', '')
            verse_num = '0' + verse_num if len(verse_num) == 2 else '00' + verse_num
            current_verse = verse_num
            verses[current_verse] = []
        elif current_verse is not None and line:
            verses[current_verse].append(line)
    return verses

In [13]:
split_text_into_verses('/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John_new.txt')

{'001': ['сямянхат ӈули” нюрте” э’ вада танявы,',
  'вада нумгана мэвы,',
  'пыда нум’ ӈэвы.',
  'вада нюрте” эхэд нумгана мэвы.',
  'хусувэй ӈамгэ няданда ӈадимы.',
  'хусувэй ӈадимы ӈамгэ пыдасиципой” ӈадимзь нивэда пирас”.',
  'вадахана ил’ танявы,',
  'тикы ил’ ненэцие” яляӈэ таравы.',
  'тикы яля пэвдяхартахана ялэмды,',
  'пэвдя сита пирда” ле ни пирас”.',
  'нум’ ӈэдаравы',
  'ӈопой хасава танявы,',
  'нюмда иоанн ӈэвы.',
  'пыда яля’ нямна ненэсям’ ваде” манзь товы.',
  'тиканда хусувэй хибя сита намд” махаданда',
  'ялян’ пунраӈгу” ни” им’.',
  'пыдахавада яля нивы ӈа”,',
  'хуркавна ӈо” пыда яля’ нямна ненэсям’ ваде” манзь нум’ ӈэдаравэда.',
  'яляхав, ненэся яляхав,',
  'хусувэй ненэцям’ ялэмдамбада,',
  'мале та’ мальӈгана я’ тир’ ни’ ӈадимдавы.',
  'пыда я’ тиркана танявы,',
  'я’ тир” няданда ӈадимы ӈэбта ӈод”,',
  'я’ тир’ тер” сита ни” хамэда”.',
  'пыда харта  ӈамгэхэта то.',
  'харта ненэциеда сита сейхато’ ня”маван’ ни” харва”.',
  'сита сейхато’ ня”амвэхэв” нянда пунрэяд”.',
  'тикы ненэцяӈг” пыда нум’ ню” ӈэсь ватодамдо’ ми”ӈа. пыдо’ ненэця’ паӈгхад, пыхыд’ харвабцоход, ненэця’ ватоход соявы” ни” ӈа”, нумгад соявы”.',
  'вада ненэцяӈэ хая, поӈгана” илелъй”.',
  'пыда тихинда сянавасавэй, ненэсясавэй.',
  'маня” юнанда танявам’ манэ” ӈаваць.',
  'тикы юнда ӈопой ню ӈэванда е”эмня нисянда ми”мы.',
  'иоанн пыда нямнанда ненэсям’ ваде” ӈась,',
  'ненэцяӈг” сёнда ӈардан’ лахана:',
  '«ваде” мэми – тикы, ти мэна.',
  'мань тарем’ мадамзь:',
  '‹пудни тованда нядни ва”ӈа,',
  'соявани нерня мале ӈаха” на танясь› ».',
  'маня” малмбой’ няданда ӈэда сянавам’ етри’ панаць ня”марпива”.',
  'моисей’ сер’ ватом’ ня”маваць, иисус христос’ сер’ сянавам’, ненэсям’ ня”мава”.',
  'сяхаӈгарт’ хибяхарт',
  'нувм’ нивэда манэс”.',
  'нисянда сейхана мэна ӈопой нюрида –',
  'нум’ няна” нум’ хурка ӈэвамда ӈадимдеда.',
  'иудей” иерусалим маркад ханондани,',
  'левит хибя ӈэвамда хонраванзь ӈэдарабто’,',
  'иоанн’ сыро” мида :тарцяць.',
  'иоанн хуркари таялци”, тидпой” вахалъй”:',
  '«мань христосадм’ нидм’ ӈа”».',
  'пыдо’ сита хонра”: «тиканда хибян?',
  'илиян ӈэдакэн?',
  '» пыда ма: «нидм’ ӈа”».',
  'ӈани’ хонрадо’:',
  '«тикы нум’ вади вадетан?',
  '» пыда ӈани’ ма: «нидм’ ӈа”».',
  'пыдо’ нянда вахалъяд”:',
  '«тиканда хибян?',
  'сидна” ӈэдаравэхэ” на” ӈамгэм’ хэтаӈгува”?',
  'харт нямнанд ӈамгэм’ вадетан?',
  '» нум’ вади вадета исайя’ вади” мана иоанн тарем’ вахалъй”:',
  '«мань вэӈго яхана тюрыта вабцадм’:',
  '‹нум’ ерв’ сехэрым’ тидхалера”› ».',
  'тикы товы” ненэцие” поӈгана фарисей” танявы”.',
  'пыдо’ сита хонра”:',
  '«христосан ниб” нанд ӈа”, илиян ниб” нанд ӈа”,',
  'тикы нум’ вади вадетан ниб”нанд ӈа”,',
  'ӈамгэ хэхэдаӈгурӈан?',
  '» иоанн няндо’ вахалъй”:',
  '«маньзяван икана хэхэдаӈгурӈадм’.',
  'поӈгананда” хибяхав ну, пыдара” ехэрара”.',
  'пыдахавада пудни тованда, маньзяв нянани те”мехэртада ека ни серос” ».',
  'тикы” сер” иордан яха’ тяхана ӈэда',
  'вифанияхана ӈэвы”.',
  'тикы яхахана сяхари’ иоанн хэхэдаӈгурмы.',
  'нябимдей яляхана иоанн нянда миндя иисусм’ манэць вахалъй”:',
  '«нум’ ху’ сую, ти мэна!',
  'я’ тир’ . хэбяхам’ пыда ха”авраванда.',
  'пыда нямнанда мань тарем’ лаханадамзь:',
  '‹пудни тованда нядни ва”ӈа,',
  'пыда соявани нерня мале ӈаха” на танясь›.',
  'мань сита ехэрадамзь,',
  'израиль’ тер” сита хамэдавандо’ е”эмня ӈадьбя” ни икана хэхэдаӈгованзь тодамзь ».',
  'иоанн манэ” мыда вадець лахана:',
  '«хэбидя индад’ голубьм’ нюбета нув’ сармикадрев’ нув’ няд ниндя ха”мавам’, тадтикахад нинянда хаёвам’ манэ” ӈадамзь.',
  'мань сита ехэрадамзь.',
  'си”ми икана хэхэдаӈго ӈэдаравы няни тарем’ мась:',
  '‹хэбидя индад’ хибя ни’ ха”мавам’, тадтикахад нинянда хаёвам’ пыдар манэтар,',
  'тикы, хэбидя индкана хэхэдаӈгода›.',
  'мань манэ” ӈавась, ӈадьбя” ни тидпой” мадм’:',
  'тикы – нум’ ню».',
  'тад нябимдей яляхана иоанн ӈани’ сидя тохоламбадамда няць ну.',
  'иисус хэвувнанда ядвы.',
  'сита манэ” манда сер’ иоанн ма:',
  '«нум’ ху’ сую, ти мэна!',
  '» тикы вадида намда, сидя тохоламбадахаюда иисус’ пумна ялъяха’.',
  'иисус пуня’ сылы”,',
  'пумнанда яднаха” манэць хонарку:',
  '«ӈамгэн’ харвади’?',
  '» пыди’ маӈаха’:',
  '«равви ,',
  'хамэдита– ‹сидна”тохоламбадава”›)',
  'пыдар ханяна илен?',
  '» иисус ма: «тоди’, манэтари’ ».',
  'пыдо’ ӈобкана хая”,',
  'ханяна илевамда пыди’ манэ” ӈади’,',
  'тикы яля’ иисусхана мэӈаха’.',
  'та’ мальӈгана ялей тет час ӈэвы. нябиюм’ иоанн’ вади намдавы, тадтикахад иисус’ пумна ял”мы” – андрей пыда симон пётр’ папа ӈэвы.',
  'нюрте” э’ андрей хасава  нямда – симонм’ хо, нянда ма:',
  '«мани’ мессиям’ хони’ ».',
  'тикы грек’ вадавна «христос»',
  'андрей хасава нямда иисусан’ тэврада.',
  'иисус нянда сылаванда сер’ ма:',
  '«пыдар симонан, иоанн’ хасава нюн.',
  'тад нерня’ нюмл кифа ӈэӈгу ».',
  'тикы грек’ вадавна «пётр»**.)',
  'Нябимдей яляхана Иисус Галилея ян’ хэсь таслада',
  'филиппам’ хованда сер’ нянда ма: «пумнани ту”».',
  'филиппхав вифсаида хардахад ӈэвы.',
  'андрейха’ пётарк’ ӈани’ таняд ӈэвэхэ’.',
  'филипп нафанаилм’ хо”махаданда ма:',
  '«маня” моисей ватохонанда падвым’,',
  'нум’ вади вадети” падвым’ хова”.',
  'пыда иисус – иосиф’ хасава ню, назаретхад ӈа».',
  'нафанаил ма: «назаретхад ӈамгэ сава таняӈгу?',
  '» филипп нянда ма: «ту”, манэтарава ».',
  'иисус нянда миндя нафанаилм’ манэць,',
  'нямнанда вахалъй”:',
  '«ненэся израиль’ терхав ти, пыда хэдта яӈгу ».',
  'нафанаил нянда ма:',
  '«ханяд си”ми теневан?',
  '» иисус ма”нив’: «филипп’ сит хаё” мя’ нерня, смоковницам’ нюбета ӈодя’ пя’ ӈылна мэнаханд сит манэ” ӈадамзь ».',
  'нафанаил нянда ма: «равви!',
  'пыдар нум’ нюн, пыдар израиль’ параӈодан ».',
  'иисус тикы вади намда, тарем’ вахалъй”:',
  '«смоковницам’ нюбета пя’ ӈылна мэ”мамд нянд вадесо” махадани няни пунрэйн?',
  'ненэй манэ” мандахабид тамна неры” ».',
  'иисус тамна тяха’ лахана:',
  '«ненэся, ненэся нянда” мадм’,',
  'пыдара” нув’ няра’',
  'сидя’ ня’ няӈгармам’ манэтада”.',
  'ненэця’ нюӈэ нюмдебада’ ни’',
  'нум’ юне ядэлани” тю”уд ха”мормам’, танаӈгавам’ манэтада” ».'],
 '002': ['няхаромдэй яляхана галилея яхана ӈэда кана хардахана тюва яля ӈэвы.',
  'таняна иисус’ небя мэвы.',
  'иисус ӈо” тохоламбадита ня’ ӈобтарем’',
  'таня’ хамы” ӈэвы”.',
  'няръяна сяркандо’ сусава’ сер’,',
  'иисус’ небя иисусан’ вахалъй”:',
  '«сяркадо’ суса ».',
  'иисус нянда ма:',
  '«неӈэй, мани’ тикахана ӈамгэ серони’ таня”?',
  'мань ёльцями тамна товдавэй ».',
  'небяда манзаранаха” ма:',
  '«пыда ханзер” ма,',
  'пыдара” тарем’ ӈада” ».',
  'таняна мат” ӈарка” я пэ ид’ ед танявы.',
  'иудей” тикы ед’ тер’ икана нибтарасетвы”.',
  'хусувэй ед юр’ мян’ литрам’ тер” мы.',
  'иисус манзаранаха” ма”нив’:',
  '«ед икана панаць тердейда” ».',
  'пыдо’ икана тю”уй варандо’ ӈэсонд’ пандэйдо’.',
  'тикы’ пуд иисус няндо’ ма:',
  '«тедахав’ таняд идм’ сахалӈада”,',
  'тадтикахад тюва яля’ серм’ пэртан’ ханара” ».',
  'тадтикахад пыдо’ тикы ненэцянд’ идм’ хана”.',
  'тюва яля’ серм’ пэрта няръяна сяркаӈэ хэвы идм’ ӈэрӈада.',
  'пыда тикы сярка ханяд ӈэвахад ехэрась, идм’ сахалмыри” теневаць.',
  'тюва яля’ серм’ пэрта нелебада хасавам’ хаӈа, тадтикад ма:',
  '«хусувэй ненэць’ нерде сава сяркам’ ӈадимдесеты,',
  'ненэцие” ябело” махад вэва сяркамда ӈабтасеты,',
  'пыдахавар сава сяркам’ тев’ ёльцянд’ лэтмбавэранё” ».',
  'тикы сер” иисус’ галилея яхана ӈэда кана хардахана сертавы нюртей ненадо сер” ӈэвы.',
  'таняна юнамда ӈадимдеда,',
  'тиканда тохоламбадида нянда пунрэяд”.',
  'тикы’ пуд небямда няць, нида няць, тохоламбадида няць капернауман’ хая. сянхав яля’ таняна мэ”.',
  'иудей” пасха’ хахаялма’ сер’, иисус иерусалиман’ то.',
  'хэбидя хардахана хороби, хуво, голубьм’ нюбета нув’ сармик мирдапади манэ” ӈа. тикы” хавна таняна ӈамдёвы есь тадабади манэ” ӈа.',
  'иисус иняхад садкосям’ серта, хэбидя хардахад мирдатини хоробисавэй’, хувосавэй’ мал’ ӈокхандо’ питаръяда,',
  'есь тадабади” есьдо’ вабтъяда, тольдо’ пынделабтэйда.',
  'голубь мирдападаха” тарем’ ма:',
  '«тюку мал’ хэвня’ ханэйда”!',
  'нисяни мядм’ ӈавори мирдапалава мя”ӈэ нёра” сертабю”!',
  '» тохоламбадида хэбидя падаркана падвы',
  'тюку вади тензибте”:',
  '«мят ялыба харвобтавами  сёнзяни мюд си”ми ӈаворӈа ».',
  'тиканда иудей”',
  'иисусан’ ма”:',
  '«тарем’ ӈэсь ватомд ӈамгэ ненадо серка” на манэ” лабта пиртар?».',
  'иисус няндо’ ма:',
  '«тюку хэбидя харадм’ тахабтара”,',
  'маньзяван няхар” яля’ пирка” на яӈор’ ӈабтаӈгув!',
  '» иудей” тикы вадаха” тарем’ ма”:',
  '«тет юкад вата мат” по’ тюку хэбидя харадм’ сертабидонзь, пыдахавар няхарли” яля’ яӈор’ ӈабтаванзь пэрӈар?',
  '» иисусхав хэбидя харадм’ вадець, харта пыхыданда нямна лаханась.',
  'иисус’ ха”махаданда илелманда сер’, тохоламбадида тикы вадида тензибтевы”.',
  'тикы’ пуд хэбидя падарт’, иисус’ ваде” мы вадаха” пунрэяд”.',
  'пасха хэбидя ялэ” ямбхана иисус’ иерусалимхана мэванда мальӈгана ӈока ненэць’ ненадо серо сертавамда манэ” ӈаць,',
  'тадтикахад нянда пунрэйдаць.',
  'иисусхав хусувэй ненэцям’ тенева, няндо’ нись ен”.',
  'пыда ненэця’ сёнзя’ мюй’ ӈамгэ хадкэӈгавахад теневавы. ӈадьбята ненэця’ нямна ӈэда манэ” лабт” нянанда нивы тара”.'],
 '003': ['фарисей” поӈгана никодимам’ нюбета, иудей” ӈоб” ӈарктадо’ танявы. ӈобӈгуна пи’ пыда иисусан’ то,',
  'нянда тарем’ вахалъй”:',
  '«равви, маня” тенева, пыдар нум’ ӈэдаравы сидна” тохоламбадава”.',
  'нумзяда ненэць’ пыдар сертабада ненадо серод серта нида пирас” ».',
  'иисус ма:',
  '«мань ненэся, ненэся нянд мадм’, хибя яӈор’ нибта соя”,',
  'тикы нум’ параӈодадавам’ манэць нида пирас” ».',
  'никодим нянда ма:',
  '«ӈармы ненэць’ ханзер” яӈор’ сояӈгу? ненэць’ яӈор’ ню’ ӈэся’ мю’ пакалць пир” ӈада?',
  'тикы’ пуд нябимдей’ соябта серо” ӈа?» иисус ма: ненэся, ненэся нянд мадм’,',
  'хибя икад, хэбидя индкад нибта соя”,',
  'тикы нум’ параӈодадаван’ тюсь нида пирас”.',
  'ӈаяхад соявы – ӈая, индкад соявы – инд”.',
  'мань ваде” мэхэ” ни нён пысаӈг”: ‹пыдара” тю”уд соябта” тара›. мерця ханяд харва, таняд пупида.',
  'мунда намдорпат ӈо”,',
  'пыдар ханяд ӈэвахаданда,',
  'ханя’ хэвахаданда ехэран.',
  'хусувэй хэбидя индкад соявы ӈани’ тарця ».',
  'никодим сита хонра:',
  '«ханзер” тарця ӈэсь пир” ӈада?',
  '» иисус тикы вадахата ма:',
  '«пыдар израильм’ тохоламбадананё”,',
  'ханзер” тарцям’ нир хамэдамбю”?',
  'мань ненэся, ненэся нянд мадм’:',
  'маня” ӈамгэм’ теневава”, тикым’ ваде” ӈава”, ӈамгэм’ манэцава”, тикым’ манэ” лабтамбива”.',
  'пыдахавара”',
  'манэ” лабтма” сёнзяханда” нида” пэмбю”.',
  'я’ ила’ нямна ӈэда лахарёхортаха” ни нида” нё” пунрю”, ханзер” нув’ нямна ӈэда лахарёхо” ни пунраӈгуда”?',
  'нумгад ӈэда ненэця’ нюӈэ нюмдебада’ хавна, хибяхарт нув’ няю’ хэвы ненэць’ яӈгу.',
  'ханзер”  вэӈго яхана моисей ӈабтацавэй халым’ тю”у’ иласа, тарем’ ненэця’ нюӈэ нюмдебада тю”у’ илавы ӈэӈгу.',
  'ӈадьбята хусувэй нянда пунрёда [ни хаӈгу”,]',
  'няданда малсяда илам’ ня”маӈгу.',
  'нум’ тюку я’ тир’ терм’ саць мэневанда нид, ӈопой нюримда ми”мы. нюхунда пунрёда хусувэй хибя ни хаӈгу”, малсяда илам’ ня”маӈгу.',
  'нум’ нюмда я’ тир’ терм’ судева’ е”эмня ӈэдаравэда ни ӈа”, нюнда сер’ я’ тир’ терм’ ӈэдаванзь ӈэдаравэда.',
  'нюхунда пунрёда судевы ни ӈэӈгу”.',
  'нянда ниня пунрёдахав мале судевы.',
  'пыда нум’ ӈопой нюнда нюмд’ ниць пунра”.',
  'яля я’ тир’ теран’ ӈадимясь. ненэцяӈгав” яляхад пэвдям’ саць мэневандо’ нид, мале танаравы”.',
  'пыдо’ сертабада серодо’ вэнзукубтыць.',
  'вэвам’ сертабада хусувэй хибя ялям’ волтамби,',
  'харта серода нива ӈадима’ е”эмня ялян’ ни мий”.',
  'ненэсявна иленахав ялян’ минд”нив’.',
  'сертавы серода нувм’ няд” мяць ӈэвандо’ е”эмня серода ӈадяӈгу” ни” им’ ».',
  'тикы’ пуд иисус тохоламбадида няць иудея ян’ хая.',
  'таняна нянандо’ иле, ненэцие хэхэдамби.',
  'та’ мальӈгана ӈо”, салимахад хахаяда енон яхана иоанн ненэцие хэхэдамбись.',
  'таняна и” ӈока ӈэвы.',
  'ненэця” нянда хэхэдаӈгурманзь турмы”.',
  'та’ мальӈгана иоаннм’ тамна нивэдо’ сяр”.',
  'иоанн’ тохоламбада” иудей’ тэнзм’ мэта ненэця’ ня’ нярумдава’ нямна тасалкурць пэяд”.',
  'иоаннан’ тэввандо’ сер’ хонрадо’:',
  '«равви, ти, иордан яха’ тяханяна нянанд мэвы ненэцял – ненэцяӈг” ваде” мэр, ненэцие хэхэдамби.',
  'тиканда хусувэй хибя нянда миӈа ».',
  'иоанн няндо’ ма:',
  '«нум’ тарем’ таслаб”, ненэць’ ӈамгэхэртм’ ни ня”маӈгу”.',
  'ӈамгэм’ вадесо” махани пыдара” харта” инзеледаци”,',
  'вадини тарцяци”: ‹мань христосадм’ нидм’ ӈа”,',
  'пыда тованда нерцюна, нум’ си”ми ӈэдарась›.',
  'нем’ мэмбадахав – нелевнда хасава. нелевнда хасава’ сава няхав тэри тиканда нухуя,',
  'нянда инзеле.',
  'вабцамда намдванда сер’ маймбаӈгу.',
  'мань ӈо” теда’ сёнзяни мюй маймбабцохона пан” ӈа.',
  'пыдахавада теда’ тю”у’ мимбата тара” нив’, маньзяван таси’ мимба” ни тара.',
  'тю”уд ха”амвэхэв',
  'сямянхат ва”ӈа.',
  'я’ ниня иленахав яхад пере,',
  'вадетида я’ ила’ няримна ӈа”.',
  'нув’ няд ха”амвэхэв сямянхат ва”ӈа.',
  'манэ” мыда, намдвыда вадепата ӈо”,',
  'манэ” лабтата хибяхарт сейханда нида ня”ам”.',
  'манэ” лабтата сейханда ня”амвэхэв',
  'нум’ ненэся ӈэвам’ тид” манэ” лабтамби.',
  'нум’ ӈэдаравым’',
  'нум’ хэбидя индкана пандамбида,',
  'ӈадьбята пыда  нум’ вади мэ”ӈа.',
  'нисяюм’ нюмда ёльце мэневанда нид,',
  'ӈудахата хусувэй ӈамгэм’ мал’ ми”мыда.',
  'хибя нум’ нюн’ пунры, тикы малсяда илӈгана иле.',
  'нум’ ню’ мунд’ ниня намданахав илам’ нида манэт”, нум’ няданда пили” нензюмда ».'],
 '004': ['иисус’ тохоламбадида, хэхэдамбада ненэциеда иоаннхад ӈока ӈэва юн фарисейха” тэввы”.',
  'ӈабцакаванда иисус нивы хэхэдаӈгу”,',
  'тохоламбадида хэхэдаӈговы”.',
  'иисус тарця мунм’ намда, иудея яхад хая, ӈани’ галилея ян’ нэкалӈада.',
  'самария явна хэбта таравы. самария яхана ӈэда сихарьм’ нюбета хардавна ӈадимя.',
  'тикы харад лата я’ хэвхана ӈэвы. тюку я ӈавнанда иаков хасава нюхунда – иосифан’ ми”мэда.',
  'таняна иаков’ нелава танявы.',
  'иисус пэдёмда ӈэдабтамба, нелава’ хэван’ ӈамды”.',
  'яля’ ер’ ёльць’ ӈэвы. таня’ самария я’ тер ӈоб” не нерманзь то.',
  'иисус хонрада: «итами та”ма ». та’ мальӈгана иисус’ тохоламбадида ӈаврадамдо’ тэмдаванзь хардан’ хэвы”.',
  'самария я’ тер не иисусан’ ма: «пыдар иудея я’ тернанё”, ханзер” нядни – самария я’ терхад идм’ хаӈан?»',
  'иудей” самария я’ тер” ня’ поёдо’. иисус нянда вахалъй”:',
  '«пыдар нум’ тамбада ӈамгэ’ нямна теневавы ӈэб” нанд, хибя няданд идм’ хамам’ теневавы ӈэб” нанд,',
  'пыдар харт няданда ханаӈгунась, тадтикахад пыда харта нянд иленя идм’ татась ». не ма:',
  '«мань ервав!',
  'нелава та’ пирувнанда ёрява, пыдар сахалкосяӈгартар яӈгунё”. тиканда ханяд иленя идм’ ханаӈгур?',
  'иаков нисяхадана” ӈаркаӈэ пыхыдамд тосар? пыда няна” тюку нелавам’ тавы.',
  'пыда, хасава нюда, тадтикахад харта вадавы сармикада тюку нелавахад идарӈаць ».',
  'иисус нянда вахалъй”: «хусувэй хибя тюку идм’ ӈэрта яӈор’ идарман’ харбилаӈгу.',
  'мань мипада икавахадани хибяри‑хибя ит’ харвабцоходанда юраӈгу.',
  'мань ми”манда икавами нянанда малсяда илан’ сита минрена лохорта и”ӈэ ханда ».',
  'не нянда ма: «ервэй! тарця итами та”ма, тиканда мань ит’ харвабцоми яӈгод” нив’, нерманзь тюкон’ вунидм’ турт”».',
  'иисус нянда ма: «хань”, вэсул хай”,',
  'тадтикахад ӈани’ туин ».',
  'не ма”нив’: «мань вэсу” ми яӈгу ».',
  'иисус нянда ма: «пыдар ненэсян, вэсул ненэся яӈгу.',
  'пыдар самляӈг вэсулась, теда’ нятахавар вэсул вуни ӈа”.',
  'вадид ненэся” ».',
  'не нянда ма:',
  '«нум’ ерв!',
  'мань сырпа” ни, пыдар нум’ вади вадетан.',
  'нисянана” тюку хой’ ниня туёцеты”,',
  'пыдахавара” мада” нё”: ‹туёць’ я иерусалимхана ӈа›».',
  'иисус нянда ма: «неӈэй, няни пунрю”, ёльцянда тоб”, нисяхани туё” мара” тюку хойхана ни ӈэӈгу”,',
  'иерусалимхана ни ӈэӈгу”. пыдара” ехэрана ӈамгэн’ туё” ӈада”, маньзявана” хибян’ туё” махадана” теневава”. ӈэдаӈгова иудейхат  ӈа.',
  'ёльцянда тоб”, ӈабцакаванда мале тэвы” ма, ненэсявна туёта” индадм’ няд” мяць, ненэсям’ няд”мяць нисяхани туёта”.',
  'нисями ӈо”, нянда тарем’ туёти пюрӈа.',
  'нум’ – инд” ӈэ”нив’.',
  'нянда туёта” индадм’ няд” мяць, ненэсям’ няд” мяць туёпато’ тара ». не нянда ма:',
  '«христосм’ нюбета мессия’ товахад мань теневадм’. пыдахавада то”махаданда, няна” хусувэй ӈамгэм’ вадета ».',
  'тикы’ пуд иисус нянда ма: «мань тидамнё”, нянанд теда’ лаханакурӈадамнё” ».',
  'та’ ёльцьӈгана иисус’ тохоламбада” то”. иисус’ нехэна лаханакурмам’ манэ” мандо’ сер’ пысэйд”.',
  'иисус’ ӈамгэн’ харвава’ нямна,',
  'ӈамгэ не’ ня’ лаханава’ нямна',
  'ӈобкартадо’ сита ни хонра”.',
  'тикы не ита ӈэсям’ хае, харад’ няна хая.',
  'ненэцяӈг” ма:',
  '«хаяда”, техэ малханда хурка ӈэвами явнанда ваде” мы ненэцям’ манэ” ӈара”!',
  'христосхав ниб” нандав’ ӈа”?',
  '» хардахад ненэця” иисусан’ хая”.',
  'тикы ёльцьӈгана тохоламбадида сита хонрамби”: «равви, ӈамгэкодар ӈав” ма ».',
  'пыдахавада няндо’ тарем’ ма: «маньзяван пыдара” ехэрана ӈаврами таня ». ӈадьбято’ тохоламбадида помнандо’',
  'нидо’ хонрамба пя”:',
  '«нянда хибяхав ӈаварм’ тэврамбавэкы?» иисус няндо’ ма: «си”ми ӈэдаравэни ватом’ сертабавами,',
  'тадтикахад серта малевами – ӈаврахаюни, тихи’.',
  'пыдара” тарем’ нисяда” лахан”? ‹тет иры’ хэ”мяхад нянь’ ӈуво” сэв ма”ламбава’ ёльць’ тута›.',
  'нянда” мадм’, сыркарӈада”,',
  'нянь’ ӈуво” сэв” вадюлава я” ялмыд”, мале малкова’ ёльць’ то. нянь’ ӈуво” сэв ма”ламбада недбям’ ня”ма,',
  'малсяда илан’ тэвва’ е”эмня таром’ сертаби. нянь’ ӈуво” сэв моёпадаха’,',
  'нянь’ ӈуво” сэв ма”ламбадаха’ ӈобкана маймбаӈгуху’.',
  'тюку вада’ хара явнанда ӈа, тарця:',
  '‹нюрте” эюм’ нянь’ ӈуво” сэв моёпи, нябиюм’ нянь’ ӈуво” сэв ма”ламби›.',
  'мань ӈани нита” манзара” мавна малкурманзь сидда” ӈэдарадм’.',
  'ӈабцакаванда нида” варемдо’ мэць манзараць, пыдахавара” нита” манзара” маха” таркэйда” ».',
  'самария я’ тер нехэв манэ” мыда‑намдавыда ханяримна‑таняримна ваде” яда:',
  '«пыда ӈахат иле”мями ӈарханда ваде” ӈадась ».',
  'тикым’ намдвандо’ сер’ тикы хардахад ӈэда ӈока самария я’ тер иисусан’ пунрэяд”.',
  'иисусан’ тэв” махадандо’, самария я’ тер” сита нянандо’ мэсь хонрамби”.',
  'пыда таняна сидя яля’ мэ.',
  'нянда инзеле” мяхадандо’',
  'тамна ӈока ненэць’ нянда пунрэяд”.',
  'пыдо’ нен’ ма”: «тедахав’ пыдар ваде” мэрихитат вунива” пунрю”,',
  'хар” на” нянда инзеле” мяхадана” пунрыва”.',
  'тедахав’ маня” теневава”, пыда ненэся я’ тир’ тер” ӈэдаӈгода ». сидя яля’ хэ”мяхад, тикы яхад иисус галилея ян’ хая.',
  'тад ӈо” пыда харта явнанда лаханась:',
  '«харта яхананда нум’ вади вадетам’ нидо’ таро” ла” ».',
  'иисус иерусалимхана мэванда мальӈгана, хэбидя  яляхана хуркари ненадо серо сертабавы.',
  'ӈока галилея я’ тер хэбидя ялян’ товы”, тикан’ сырмы”.',
  'ӈадьбято’ галилея ян’ товы иисусм’ манэ” мандо’ сер’, пыдо’ маймба ядабтадо’.',
  'тикы’ пуд иисус галилея яхана ӈэда кана хардакон’ ӈани’ тэвы”.',
  'сяхаӈгав’ тикы хардахана идм’ няръяна сяркаӈэ сертадась. та’ мальӈгана таняна ӈопой параӈода’ марцьхы мэвы.',
  'капернаум хардакохона хасава нюда хаӈгурць юседавы.',
  'иисус’ иудеяхад галилеян’ товам’ намда, пыда иисусан’ то, хынумба пяда: «капернауман’ нянани ту”ма.',
  'хаван’ харвана хасава нюми савумдадва ».',
  'иисус нянда ма:',
  '«хибяхартара” ненадо серо, и’ хэбиле” мя серо манэ” мадавэй’ пунра нида пирас” ».',
  'параӈода’ марцьхы нянда ма:',
  '«нум’ ервами, нюни хава’ нерня ту”ма ».',
  'иисус нянда ма: «мяканд хань”, нюр илеӈгу ».',
  'тикы ненэць’ иисус’ вадаха” пунрэй”, тадтикахад хая.',
  'ядаванда сер’ хабида сита хо”, ма”:',
  '«нюр иле».',
  'ӈацекы’ нися сяха’ нюнда савуво” мам’ хонра.',
  'хабида ма”: «теняна яля’ ер’ ӈопой часхана ӈаянда ядё ха”мыць ». ӈацекы’ нися нюнда сяха’ едясялмам’ хамэдада.',
  'иисус’ нянда тарем’ мама’ мальӈгана: «мяканд хань”, нюр илеӈгу », та’ мальӈгана нюда едясялмы.',
  'тиканда пыда мяд’ терсавэй’ иисусан’ пунрэяд”.',
  'тикы сер” иисус’ иудеяхад галилеян’ тэв” махаданда нябимдей ненадо сертавы серта ӈэвы.'],
 '005': ['тикы’ пуд иисус иудей” хэбидя яля’ ёльцьӈгана иерусалиман’ хая.',
  'таняна хуво” вад’ хэвхана меӈга танявы, тикы меӈга’ нюм’ еврей’ вадавна «вифезда ».',
  'самляӈг синдёда тюӈгалавада танявы.',
  'мюнянда хуркари” хаӈгурта”,',
  'сэвсяда”, мэдна”, хэвдо’ хабэй” юседа”.',
  '[пыдо’ ид’ манзадавам’ ӈатевы”.',

In [14]:
split_text_into_verses('/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/yrk_cyrillic_Mark_new.txt')

{'001': ['нум’ ню’ – иисус христос’* нямна ӈэда маймбабцо юн’ нерденя. нум’ вади вадета’ – исайя’ падаркана тарем’ пады:',
  '«ти, неранд няд сехэрэдамд хамэдавандаӈэ мань нув’ юне ядэланами ӈэдарадм’».',
  '«вэӈго яхана тюрыта’ вабц со:',
  '‹нум’ ерв’ сехэрэдамда хамэдада”,',
  'недамда ненземдара”›».',
  'тарем’ иоанн вэӈго ян’ ӈадимя.',
  'хэхэдаӈгованда сер’ ненэцие ханзь тарем’ ма:',
  '«хэбяхыда” хаейда”,',
  'хэхэдаӈгуда”,',
  'тиканда нум’ хэбяхыда” ха”авраӈгуда».',
  'иудея’ я’, иерусалим’ марад’ тер” малмбой’ нянда миӈа”.',
  'хэбяхыдо’ индо’ ядан’ ваде”ядо’.',
  'иордан’ яхахана иоанн сиддо’ хэхэдамби.',
  'иоанн',
  'маха ху”ла юно’ – верблюд’ таркад паӈгалмы паным’ мэ”ӈа,',
  'ёнэнда тяхана тобъёва ни сяры,',
  'ӈавраданда явна маирти, юрите”э пилю” юре мэ”ӈа.',
  'ненэцие ханзь тарем’ лахана:',
  '«пумнани миндя нядни ва”ӈа.',
  'ӈари” маньзяван нянани пибита те”ме таси’ хо”леркая екахарта ни серос”.',
  'мань сидда” икана хэхэдамбидм’.',
  'пыда сидда” хэбидя индкана хэхэдамбаӈгу».',
  'тикы ялэ” ёльцьӈгана галилея’ яхана ӈэда назаретхад иисус то.',
  'иордан’ яхахана иоанн сита хэхэда.',
  'икад тарпаванда сер’ тикы’ минда иисус лакри’ нув’ няра’ няӈгармам’ манэ”ӈа.',
  'голубьм’ нюбета нув’ сармикадарев’ хэбидя индад’ нянда ха”мотавам’ манэ”ӈа.',
  'нув’ няд лаханана мамононда:',
  '«пыдар мань мэненами нюми ӈэ” нинав’,',
  'сейханани поин».',
  'таминда тикы’ пуд хэбидя инд” иисусм’ вэӈго ян’ ханада.',
  'иисус’ вэӈго яхана тет ю” яля’  мэва’ сер’ сатана* хэбяха серк” сита ханзь хорпи.',
  'иисус я’ сармик” поӈгана мэ,',
  'тикы ялэ” ямбха”на нув’ юне ядэлана” сита нядаби”.',
  'иоаннм’ сяр”махадандо’ нум’ маймбабцо юнм’ ваде”манзь иисус галилеян’ хая.',
  'пыда ма:',
  '«ёльцянда тэвы”.',
  'нум’ параӈода’ я нядна” хахаялма.',
  'хэбяхыда” хаейда”,',
  'маймбабцо юнан’ пунрыда”».',
  'галилея’ то’ хэвувна миманда сер’ иисус поӈгам’ моёпадаха’ – симонм’, андрейм’ манэ”ӈа.',
  'андрей – симон’ папа ӈэвы.',
  'пыди’ ёртяха’.',
  'иисус нянди’ ма:',
  '«пумнани тоди’, мань сидди’ ненэцие нумд’ тэврамбадаӈэ сертаӈгудм’».',
  'пыди’ тикаринди’ ӈод” поӈгади’ хае, пумнанда пяди’.',
  'ӈамгэ’ пират’ хэ”мяхаданда,',
  'пыда ӈано’ мюня поӈгади’ сэдорпадаха’: зеведей’ нюм’ – иаковм’, иаков’ папам’ – иоаннм’ манэ”ӈа.',
  'тикаринда ӈод” нянда хаӈахаюда. нисямди’ манзаранита ня’ ӈано’ мюня хаеди’, пыди’ пумнанда хаяха’.',
  'иисус тохоламбадита ня’ капернаум’ март’ тэвыд”.',
  'тикыринда ӈо” еврей” ныланава яляхана**  пыда ма”люӈгалава мят’ тю, ненэцие тохоламба пя.',
  'ненэця” тохоламбабцонда мэсыт’ пысаӈгаць.',
  'пыда моисей’ ватом’ теневани” то”лаха нись ӈа”,',
  'пыдхавада ӈарка ерв’ ныхым’ мэтадарев’ сиддо’ тохоламбись.',
  'та’ мальӈгана ма”люӈгалава мякана ня”маравы ненэць’ мэвы, тарем’ тюры”ӈа:',
  '«назарет’ тер иисус, нянана” ӈамгэ сел таня? сидна” хадарабтаванзь тосан?',
  'хибя ӈэвамд теневав –',
  'хэбидя нумд».',
  'иисус сита таб”ламба ма:',
  '«мунзялв”! сёнзянда мюд тарпад”!',
  '» тикаринда ӈод” ӈылекада ненэця’ пыхыдм’ ледребтехэя ӈарка тёрм’ мэць ненэця’ сёнзя’ мюд тарпы”. ненэця” мал’ ӈокхандо’ сейто’ хэсь нидо’ хонрамби”:',
  '«тикы ӈамгэ? тарця ныхым’ мэць едэй тохоламбада сер”?',
  'пыда ӈылекахарт табэдамби!',
  'пыдо’ ӈо” мунда сер’ ӈа”!',
  '» тикаринда ӈод” нямнанда ӈэда юн галилея’ я’ тиӈгэвна латы”.',
  'ма”люӈгалава мякад тарп”махадандо’, иисус тохоламбадида няць симонаха’, андрейха’ мят’ то.',
  'иаков, иоанн ӈобтарем’ нянандо’ тоӈаха’.',
  'симон’ пухуцянда небя ӈая’ ядё’ хабцяӈгана хаӈгурць юседа;',
  'хаӈгурмамда минхандо’ иисусан’ ваде”ӈадо’.',
  'хэвханда тэвхая, иисус ӈудахаданда сита тю”уку’ ила.',
  'таминда ӈо”, хабця’ няданда хэ”мяхаданда, не мядондида манзаяць пя.',
  'пэвсюмя’ няна, хаерад’ пакало”махад, хаӈгурти, ня”маравы мал’ нянда тэволэйдо’.',
  'харад’ тер” мал’ нёнда  си’ хэван’ ма”лыд”.',
  'хуркари хабцяӈга”на хаӈгурта ӈока ненэцям’ пыда савумдамби,',
  'ненэцие” сёнзь” мюд ӈока ӈылекам’ питарӈа.',
  'ӈылека” сита тенева”. ӈадьбята пыда ӈылекаха” ӈамгэхэртм’ нива ваде”ма’ няю’ табеку.',
  'хув’ мер’ нумда пэвван’ иисус юркы”,',
  'пин’ тарпы”.',
  'вэӈго ян’ хая, таняна туёць пэй”.',
  'симонхав нянанда мэна нита ня’ иисусм’ пюрманзь хая”.',
  'сита хо”махадандо’ нянда ма”:',
  '«ненэця” мал’ сит пюрӈа”».',
  'пыда няндо’ ма:',
  '«хахаяда ӈарка хардаха” хэхэва”,',
  'таняна ӈобтарем’ мань нум’ вади вадетадм’,',
  'мань тикы’ е”эмня тодамзь».',
  'ӈадьбята галилея’ я’ тиӈгэвна ӈэда ма”люӈгалава мяка”на нум’ вади ненэцяӈг” ваде”ӈа, хаӈгурта ненэцие” ӈылекы питарпи.',
  'мерёда ниня тораӈгана ненэць’ иисусан’ то.',
  'неранда няд пулыта ни’ мо”нахая хынумда вахалъй”:',
  '«харвабцонд таняб”, си”ми хабтумда пиртан».',
  'иисус сита сялилӈа,',
  'ӈудамда вэӈгалахая',
  'нянда ӈодь’ теба ма:',
  '«ханядм’ харва”, тадхав хабтув”».',
  'минхандо’ ниня тораӈгана мерюда тора” – ӈоб’ хабтума.',
  'тадтикахад, сита ӈэдарамба иисус я”авла нянда тарем’ табекурӈа:',
  '«инзеле”, хибяхартан’ ӈамгэхэртм’ нён вадес”, ӈопой, ханонданан’ хань”, пыхыдар нянда манэ”лабтад.',
  'савумаханд  ненэцие” пунрава’ е”эмня моисей’ вади” сер’ ханм’ тэвра”».',
  'савумдавэхэв пин’ тарп”махаданда хэвы серода ханяна-таняна вадець пяйда. ӈадьбята иисус хардо” помна ӈадя ядэрць нида пирас”. хардо” хэвхы вэӈго яха”на мэсеты.',
  'тарем’ ӈо” ханяд-таняд нянда ненэця” турцеты”.'],
 '002': ['сян яля’ пирка”на иисус ӈани’ капернауман’ то.',
  'мякананда мэвамда ненэця” намдадо’.',
  'ненэцие” та’ пирувна ӈока ӈэвандо’ нид, нё’ си’ хэвхартахана нусь ядо’ яӈговы.',
  'пыда няндо’ вадида мэ”ӈа.',
  'мале сян ненэць’ хэвда хабэй нямдо’ нянда тэвра”.',
  'нямдо’ минренаӈэ тет ненэць’ таравы”.',
  'ненэцие” ӈока ӈэва’ нид, иисусан’ тэвва серта ӈоб’ яӈговы. ӈадьбята иисус’ мэсь’ я’ ний харад’ ӈэва’ нийм’ сабкадо’, ниймда ха”аврадо’,',
  'хэвда хабэйм’ пэӈасавэй’ таси’ ӈэдарадо’.',
  'иисус нянда пунрёвамдо’ манэ”манда сер’, хэвда хабэйн’ ма:',
  '«ебта’, хэбяхыд ха”мыд”!',
  '» мале сян моисей’ ватом’ теневана тикахана ӈамдёвы”,',
  'ибето’ ӈыл’ тарем’ ибедорӈа”:',
  '«ӈамгэ пыда тарем’ лахана?',
  'пыда нувм’ вэву”ӈа.',
  'нумли’ хавна хибя ненэцие” хэбяхы ха”авра пир”яда?',
  '» иисус инда ӈыл’ ибето’ ядэрабцу минханда хамэдэйда,',
  'няндо’ ма:',
  '«пыдара” ӈамгэ ибета” ӈыл’ тикы” нямна ибедорӈада”?',
  'хэвда хабэйн’ ханяӈэюм’ вадам’ хэта нензеллаха?',
  '‹хэбяхыд ха”мыд”›,',
  'нябиюм’ вада тарця: ‹юркад”, пэӈар хана”, ядэр”›.',
  'теневаванда” нямна,',
  'я’ сяр’ ниня ненэця’ ню’ хэбяхы ха”аврамба ныхыда таня».',
  'тадтикахад хэвда хабэйн’ ма:',
  '«мань нянд мадм’, юркад”, пэӈар хана”, мяканд хань”».',
  'хэвда хабэй тикаринда ӈод” юркы”,',
  'ӈока нита сыртан’ пэӈамда содахая тарпы”.',
  'ненэця” мал’ тэри пысэйд”,',
  'нувм’ саву”ӈа”, ма”:',
  '«тарцям’ манэсо”мава” сяхаӈгарт’ яӈгусь».',
  'иисус ӈани’ то’ ня’ хая. ненэця” мал’ нянда то”,',
  'пыда сиддо’ тохоламби.',
  'иисус миманда сер’, ӈэва’ мирм’ ма”ламбалавахана ӈамдёда алфеев’ нюм’ – левийм’ манэ”ӈа.',
  'иисус нянда ма:',
  '«пумнани ту”!',
  '» левий юркы”,',
  'пумнанда пяда.',
  'иисус левий’ мякана ӈаворманда мальӈгана, ӈэва’ мирм’ ма”ламбада”, хэбяхасавэй ненэця” таняна мэвы”.',
  'пыдо’ иисусм’, иисус’ тохоламбади няць ӈобкана ӈаворӈа”.',
  'пыдо’ ӈока” ӈэвы”.',
  'иисус’ пумна минзетвы”.',
  'иисус’ ӈэва’ мирм’ ма”ламбадаха”на, хэбяхасавэй ненэцяӈга”на ӈавор”мам’ манэць, моисей’ ватом’ теневана”, фарисей” иисус’ тохоламбади хонра”:',
  '«ӈамгэ пыда ӈэва’ мирм’ ма”ламбади,',
  'хэбяхасавэй ненэцие няць ӈаворӈа?',
  '» тарця вади намда иисус вахалъй”:',
  '«сензха”на лекар’ тарабцода яӈгу,',
  'хаӈгуртаха”на тара.',
  'ирт” ӈэда ненэцие хаманзь вунзядм’ ту”,',
  'хэбяхасавэй ненэцие” е”эмня тодамзь».',
  'ӈобӈгуна иоанн’ тохоламбада”, фарисей” нива ӈавормам’ мэ”мандо’ ёльцьӈгана иисусан’ ненэця” то”,',
  'хонарку”:',
  '«иоанн’ тохоламбада”,',
  'фарисей”',
  'нива ӈавормамдо’ мэ”ӈа”.',
  'пыдар тохоламбадид ӈамгэ нива ӈавормам’ ни” мэс”?',
  '» иисус няндо’ тарем’ ма:',
  '«тюва’ ёльцьӈгана нелеванда хасава’ мядонда” нива ӈавормам’ мэцеты”?',
  'нелеванда хасава’ нянандо’ мэва’ ӈэсонд’ нива ӈавормамдо’ мэць нидо’ пирас”.',
  'нелеванда хасавам’ нядандо’ ханава’ ёльця’ тоб”,',
  'та’ мальӈгана, тикы яляхана нива ӈавормамдо’ мэтадо’».',
  '«ӈахат панэн’ хибяхарт едэй емнь”мям’ ни лабцеӈгу”.',
  'тиканда едэй лабце”мя туркаванда сер’ таӈохэй паны’ пелям’ нянда ныхыбаӈгуда,',
  'сида ханяцей’ ӈарамда.',
  'тандая’ сертавы ябе идм’ хибяхарт ӈахат хоба ӈэсянд’ нида сюрпасету”.',
  'тикахана ябе и” ӈэсямда ӈадтада,',
  'ябе и” вабтомда,',
  'ӈэсянда ӈод” вомда.',
  'ӈадьбята едэй ябе и” едэй хоба ӈэся’ мю’ хамдпада».',
  'ӈобӈгуна еврей” ныланава яляхана иисус нянь’ ӈуво” вадюлававна ядэрӈа, тохоламбадида ядвандо’ сер’ нянь’ ӈуво” сэв ныдпа пя”.',
  'фарисей” сита хонра”:',
  '«сыр”, тохоламбадид ӈамгэ еврей” ныланава яляхана ниня серота серо пэрӈа”?',
  '» пыда няндо’ ма:',
  '«пыдара” сяхаӈгарт’ нисяра” толабю”?',
  'маӈг’ ёльцьӈгана, ӈаворцявандо’ мальӈгана, давид ня”мы нита ня’ ханзер” ӈэвы”?',
  'авиафар’ ӈарка ханондана ӈэванда мальӈгана,',
  'давид нум’ мят’ тювы,',
  'хано” нянё ӈавормы,',
  'няхата ӈод” мипавы.',
  'тикы ӈавар нумд’ ханонданари” ӈаворцетвыдо’».',
  'тадтикахад иисус фарисейха” ма:',
  '«еврей” ныланава яля ненэця’ е”эмня таславы.',
  'ненэць’',
  'еврей” ныланава яля’ е”эмня ӈадимы ни ӈа”.',
  'ӈадьбята ненэця’ ню ӈобтарем’ еврей” ныланава яля’ ерв».'],
 '003': ['иисус ма”люӈгалава мят’ ӈани’ то.',
  'таняна ӈудада тырабэй ненэць’ мэвы.',
  'еврей” ныланава яляхана тикы ненэцям’ иисус савумдаӈгудав’, нидав’?',
  'сита серт’ ха”авравандо’ е”эмня ӈоб’ маниедо’.',
  'ӈудада тырабэй ненэцянд’ иисус ма:',
  '«юркад”, нерняку’ нулад”».',
  'тадтикахад ненэцие хонра:',
  '«еврей” ныланава яляхана хурка серо сертаба мэта вато таня?',
  'сава серо,',
  'вэва серо пэрць тара?',
  'ненэця’ илм’ ӈэдаба,',
  'хадарабтамба тара?',
  '» пыдо’ ӈани’ мунзи”.',
  'сейсявандо’ нид иисус няндо’ нена сылы”,',
  'инда вомзь, ӈудада тырабэян’ ма:',
  '«ӈудар вэӈгалад!',
  '» ӈудамда вэӈгалада,',
  'ӈудада ӈахат ӈыхында сензума.',
  'тикы’ пуд фарисей” ма”люӈгалава мякад тарпа”махадандо’, ирод’* няти” ня’ минхандо’ иисусм’ ханзер” маядавам’ тасламба пя”.',
  'иисус тохоламбадита ня’ то’ няна хая”.',
  'галилеяхад пумнанда ӈока ненэця” хая”.',
  'иисус’ сертабада серо” юне” хари намда, ӈули” ӈока ненэця” иудеяхад, иерусалимхад, идумеяхад, иордан’ яха’ тяхад, тир’ няби сидон’ хэвхы яхат ӈобтарем’  нянда то”.',
  'иисус ӈока ненэцие савумдавы.',
  'хуркари хабцяӈга”на хаӈгурта” сита хахаялтеван’ харва, нянда минзь тирцькута”.',
  'ӈадьбята ӈока ненэцие” сита тыеромдавоӈгад иисус тохоламбадахата пыда е”эмнянда ӈанокоцям’ хамэда табэда.',
  'хусувэхэд ханзосяди” ӈылека” сита манэць неранда няд ян’ мо”нэрцеты”, тёрсавэй’ лаханасеты”:',
  '«пыдар нум’ нюн!',
  '» иисусхав хибя ӈэвамда нива ваде”мандо’ е”эмня няндо’ я”авла табеку.',
  'тикы’ пуд иисус хой’ ни’ танэй”.',
  'хахаялтембадарида нянда хаӈа.',
  'пыдо’ нянда то”.',
  'юкад вата сидям’ тэра,',
  '[ӈэдаравэӈэ таслэйда.]*',
  'нянанда мэӈгу”ма,',
  'нум’ вади минренаӈэ ӈэдарамбаӈгудава, ӈылекы питарпа нум’ ерв’ ныхым’ мэта”ма.',
  'юкад вата сидям’ ӈабта.',
  'симонм’ петрӈэ нюмдеда,',
  'зеведей’ нюм’ – иаковм’, иаков’ папам’ – иоаннм’',
  'воанергесӈэ нюмдеӈахаюда.',
  'тикы нюв’ хамэдита тарця:',
  '«хэхэ’ мун’ ню”».',
  'андрейм’, филиппам’, варфоломейм’, матфейм’, фомам’, алфей’ нюм’ – иаковм’, фаддейм’, еврей’ тэнзри сахарамбада симонм’,',
  'вад’ саюху” иисусм’ ми”манда кариот’ терм’ – иудам’ ӈобтарем’ тэрада.',
  'иисус мят’ то.',
  'ненэця” ӈани’ таня’ ма”лыд”, тиканда иисус тохоламбадита ня’ ӈаворкарта ни” ерев”.',
  'иисус’ хахаяда нида вади” вэкат сита имда ё”мэӈэ пэрмы”,',
  'ӈадьбята сита ханаванзь яхадандо’ манзада”.',
  'иерусалимхад товы моисей’ ватом’ теневана” ма”:',
  '«сёнзянда мюня веельзевул* таня. пыда ӈылекы” ерв’ ныхым’ мэць ӈылекы питарпи».',
  'ӈадьбята иисус сиддо’ нянда хаӈгая, хара явна ӈэда лахарём’ мэць, тарем’ ма:',
  '«сатана ханзер” сатанам’ питарць пиртада?',
  'параӈода’ я’ тер” харто’ помнандо’ поёмбаб”нандо’,',
  'параӈодандо’ я мюданда тахараӈгу,',
  'тамна тяха’ нусь нида пирас”.',
  'мяд’ тер” помнандо’ поёмбабто’, мято’ пон’ нусь нида пират”.',
  'сатана’ я мюданда тахарабта, нусь нида пират”,',
  'харта техэ’ малханда тэваӈгу” – та’ ёхода.',
  'мэбета ненэця’ илебциеда мякаданда хибяхарт тале нида пират”, сита сяр”марихид илебцо” тале пиртыд”.',
  'ненэся нянда” мадм’, ненэцие” хуркари хэбяхандо’, вэвакумдёвандо’ танявы ӈэб” ӈод”, мал’ ха”маӈгуд”.',
  'хэбидя индадм’ вэвута’ хэбяхыда иланда панан’ нид” ха”маӈгу”, хэбяхыда пили” нянанда ӈэӈгу”».',
  'ханяӈы” ненэця” иисус’ сёнзя’ мюня ӈылека мэнаӈэ пэрмы”, ӈадьбята пыда тарем’ лаханавы.',
  'тарем’ мэнаханда небяда хасава нита ня’ то”.',
  'мяд’ хэвхана ну”,',
  'сита хосая ненэцям’ нянда ӈэдара”.',
  'иисус’ хэвхана ненэцие” мандал” ӈамды”.',
  'нянда ма”:',
  '«сыр”, пихиня небяр, хасава нид, [не нид]* мэ”,',
  'сит хонрамби”».',
  'тадтикахад иисус ма:',
  '«мань небями хибя?',
  'мань хасава нини хибя”?',
  '» ӈамдёди” сид” нямна саӈомда ӈэдарахая ма:',
  '«мань небями, мань хасава нини – ти” мэна”.',
  'нум’ вату нёдана” – тикы” мань хасава нини, не нини, небями».'],
 '004': ['иисус то’ хэвхана ӈани’ ненэцие тохоламба пя. ӈока ненэцие” нянда ма”лёва’ нид тохона ӈэвы ӈано’ мю’ тий”, ӈамды”.',
  'ненэцяӈгав” мал’ то’ вархана хаи”.',
  'хара явна ӈэда лахарю мэць, иисус сиддо’ хуркари” серк” тохоламби. тохоламбаванда сер’ няндо’ тарем’ ма:',
  '«инзеледа”! ти, нянь’ ӈуво” сэв моёпада нянянда ӈуво” сэв моё”манзь тарпы”.',
  'нянь’ ӈуво”  сэв моёпаванда мальӈгана, ханяӈы нянь’ ӈуво” сэв” сехэры’ ни’ ха”мыд”,',
  'нув’ сармик” то”, ӈамъядо’.',
  'ханяӈыдо’ пэ я’ ни’ ха”мыд”,',
  'ненэй янда хоба тора ӈэвы, минханда тикы яхад ӈамдэдо” сэв” тю”у’ ӈадимя”.',
  'хаерад’ тю”у’ тарпава’ сер’ нянь’ ӈамдэд” сэлӈа”,',
  'паӈгсявандо’ нид тыра”.',
  'ханяӈыдо’ нацдэй ӈуво” понд’ ха”мыд”. нацдэй ӈуво” тю”у’ вадёва’ сер’ нянь’ ӈуво” сэв” тидха”нато’ вадёда ӈэвадэяд”.',
  'тэри таросялма”.',
  'ханяӈыдо’ сава ян’ ха”мыд”,',
  'вады”,',
  'нядандо’ няхар” юд’ мэва’, мат” юд’ мэва’, юр’ мэва’ нянь’ ӈуво” сэв” вады”».',
  'иисус няндо’ ма:',
  '«хавода намдорта инзелея!',
  '» ӈока ненэцие” хэ”мяхад харта хаё”мяхаданда юкад вата сидяда, ӈани” хэвхананда мэвы” ненэця” хара явна ваде”мыта нямна сита хонра”.',
  'няндо’ ма:',
  '«пыдара” нянанда” нум’ параӈода’ я’ таклада сер’ хамэдита ӈади, ӈани” ненэцяӈг” хусувэй ӈамгэ хара явна ӈэда лахарём’ мэць ваде”мы ӈэӈгу.',
  'пыдо’ ӈани’ сэвто’ сырп” ӈод”, нидо’ мание”, хавото’ намдорп” ӈод”, нидо’ хамэдамбю”.',
  'нум’ няку’ ӈэвы ӈэбто’, хэбяхыдо’ ха”маӈгудаць».',
  'иисус няндо’ ма:',
  '«тикы лахарё’ харам’ нира” хамэдамбю”?',
  'тадтикахад ӈани лахарю” хари ханзер” хамэдаӈгуда”?',
  'нянь’ ӈуво” сэв моёпада – вадам’ моёпадараха.',
  'ханяӈы” ненэця” сехэры’ ни’ ха”амвы нянь’ ӈуво” сэвраха”.',
  'нум’ вадам’ намд”махадандо’',
  'няндо’ сатана минханда турӈа,',
  'сейхато’ ха”амвы вади хан”лэйда.',
  'ӈани ханяӈы” пэ я’ ни’ ха”амвы нянь’ ӈуво” сэвраха”.',
  'намдавы нум’ вади минхандо’ маймба сейхато’ пэмбидо’.',
  'ӈопой, паӈгсяда ӈамдэдо” то”лаха”, ӈадьбято’ пон’ иле нидо’ пирас”.',
  'сяхари’ мая’ ёльцьӈгана нум’ вадам’ волтамбади”, питарпади” ӈадимб”,',
  'пунрёбцомдо’ минхандо’ ёпидо’.',
  'ханяӈы” нацдэй” понд’ ха”амвэраха”.',
  'вадам’ намдадо’,',
  'намдавы вадидо’ ила’ саиро”, тэтерман’ харвабцу”, ӈани сямян харвабцу” тяхаворӈа”,',
  'тикы вада” сейхатато’ ян’ ха”морӈа”,',
  'таросялворӈа”.',
  'ӈани ханяӈыдо’ сава ян’ ха”амвы нянь’ ӈуво” сэв” то”лаха”:',
  'намдавы вадидо’ сейто’, ибето’ ядан’ поя ха”морӈа”,',
  'ханяӈыдо’ няхар” юд’ мэва’, нябидо’ мат” юд’ мэва’, ӈани ханяӈыдо’ юр’ мэва’ таром’ ха”аврамби”».',
  'иисус тамна тяха’ няндо’ ма:',
  '«ӈамгэ’ е”эмня серекабт тюнебада?',
  'минханда ӈарка хыдяхана  лэёмда такалпава’ е”эмня, таси’, ва”ав’ хэван’ ӈабтава’ е”эмня?',
  'нарам’ ни’ ӈабтаванзь таславы ни ӈа”?',
  'ӈобкарт таклада сер” ӈадимадавэй’ хаё нида пирас”,',
  'хуркари тале мэта сер” тю”у’ ӈадимда.',
  'хибя инзелена хавода таняна, намдая».',
  'пыда няндо’ ма:',
  '«намдорта вадахата” сававна инзеледа”:',
  'ся’ пирувна ӈамгэм’ ми”ӈада” –',
  'та’ пирувна ӈамгэм’ ня”маӈгуда”, тамна ваць хоӈгуда”.',
  'ӈамгэнда таняна’ ӈамгэда тамна тяха’ ӈокамда,',
  'ӈамгэхэртасядахад',
  'ӈамгэнда таняб” мармы ӈэӈгу».',
  'тадтикахад иисус тарем’ ма:',
  '«нум’ параӈода’ я тарця’ то”лаха.',
  'ӈопой ненэць’ нянь’ ӈуво” сэв ян’ моё”яда,',
  'тикы’ пуд пыда пи’ хоны, яля’ юркорӈа.',
  'ӈамдэдо” паӈго” тю”у’ ханзер” ӈадимяхад, вадёвахад ерме.',
  'я ӈамдэдо харта соябтамбида:',
  'пили” нерде ӈамдэдо” сэв ӈадимдемби, тикы’ пуд ӈамдэдо” ӈэва” ӈадиберӈа”,',
  'ӈамдэдо” ӈэв” мюня нянь’ ӈуво” сэв” ӈархандо’ сояӈга”.',
  'ма”лава’ ёльцянда тоб”, нянь’ ӈуво” сэв” похо”махадандо’, таминда матора мэта пидерцям’ мэць пяӈгу”».',
  'тадтикахад иисус ма:',
  '«нум’ параӈода’ ям’ ӈамгэ’ то”лахаӈэ таслаӈгува”, хурка хара явна ӈэда лахарём’ мэць вадетава”?',
  'нум’ параӈода’ я  горчица’ пя’ сэв’ то”лахако.',
  'пя’ сэв ян’ моёпава’ мальӈгана сямянхат манорокось.',
  'ян’ ха”ма”махаданда ӈамдэта мал тю”у’ ӈадиберӈа, ӈани нита нимня ӈаркаӈэ, таркаляӈгаӈэ вадюрӈа,',
  'тидхананда нув’ сармик” хэӈгадамдо’ хомби”».',
  'тарця хара явна ӈэда лахарю мэць, хамэдавандо’ пирувна няндо’ лаханась.',
  'хара явна ӈэда лахарёсипой” нись лахан”.',
  'тохоламбадарихита вади” хари хамэдито’ сер’ яӈга ваде”ядась.',
  'иисус’ поӈгэй мерцям’ янимда”ма тикы яля’ пэвсюмя’ няна иисус тохоламбадахата ма:',
  '«то’ тяханя’ хэхэва”!',
  '» ненэцие хаейдо’,',
  'ӈанонда мюня мэванда сер’, тохоламбадида сита нянандо’ хана”.',
  'ӈанонда хэвхана ӈани” ӈано” танявы”.',
  'лакри’ сата поӈгэй мерцяӈэ хая, ӈарка хамба” ӈано’ ядан’ тебвандо’ сер’ ӈаном’ икана пандамбидо’.',
  'пыркабтадота пыда ӈано’ пуй вэкана хоны.',
  'сита сидеба нянда ма”:',
  '«сидна” тохоламбадава”!',
  'хавандарахава”, нямнана” ир ӈоб’ ни няркан”?',
  '» юрка”махаданда пыда мерцям’ таӈылмда,',
  'тон’ вахалъй”:',
  '«мунзялв”! ӈэвадад”!',
  '» таминда мерцяда ӈэвадэй”,',
  'хури’ хэ”нёӈэ хая.',
  'пыда няндо’ ма:',
  '«сейда” нена” ябта”нё”!',
  'пыдара” тедари’ пунрёбцора” тарси” тянёнё”!',
  '» пыдо’ ӈули” сейсялмы”,',
  'помнандо’ няхато’ хонарку”:',
  '«пыда хибя ӈэбта,',
  'мерцяхарт, тохорт муӈганда намдорӈаха’!»'],
 '005': ['то’ тяханяна ӈэда герасин’* тер” илелава ян’ тэвыд”.',
  'иисус ӈанонда мюд ян’ ха”ма”махаданда, неранда няд хальмер” яхад товы ня”маравы не нэць’ минханда сита ядабта.',
  'пэ’ хоркадёхо”на ӈэда хальмераха”на илесетвы.',
  'хибяхарт еся иняхар таха”на сита сяра я”амвы.',
  'ӈока мэва’ ӈэда еся ха”на ядыбавыдо’, ӈудида еся иняха”на сярыбавы до’.',
  'еся ин ныдпавыда, еся таман тахабтамбавыда, хибяхарт сита янимде нивы пирас”.',
  'пыда пэ хой ха”на, хальмер” поӈгана писавэй ялэ” тюрыцетвы, пыхыдамда пэхэ” ладорпавэда.',
  'ӈа”и яхад иисусм’ манэ”манда сер’ неранда няд сюрмба пулыта ни’ ха”мы”, ӈэвада нибко”ӈа. ӈули” ӈаркавна тюрыць ма:',
  '«самянхат ӈарка нум’ ню, иисус, нянани ӈамгэ сел таня?',
  'нум’ ед’ хынумдадм’,',
  'си”ми нён маядамбю”».',
  'вахало”манда нерня иисус нянда тарем’ мамысь:',
  '«ӈылека! ненэця’ сёнзя’ мюд тар пад”!',
  '» ӈадьбята ня”маравы иисусан’ тарем’ лаха навы. тадтикахад иисус сита хонра:',
  '«нюмл ӈам гэ?',
  '» ӈылека тарем’ ма:',
  '«мань нюмми легион**, маня” ӈокава”».',
  'ӈылека иисусан’ хынумда ма:',
  '«сидна” тюку яхад хэвня’ нён питарпю”».',
  'хой’ хэвхана парась” мандал” хадырмы”.',
  'ӈылека” хынумда нянда ма”:',
  '«сидна” парась” сёнзя’ мю’ пакалць ӈэдара”ма».',
  'иисус минханда',
  'вадито’ сер’ сертада. тикаринда ӈод” ӈылека” ненэцяӈгад тарп”махадандо’ парась” сёнзя’ мю’ пакалъяд”.',
  'сидя ёнар’ мян’ парась хой’ ядхад то’ ит’ мялкада”.',
  'мал’ то’ икана хабтюмя”.',
  'парась лэтамбавы” харад’ ня’, ӈысы” ня’ хунамба хая”,',
  'ӈамгэ’ хадкэ”мам’ ваде”ӈадо’.',
  'ненэця” тикым’ манэ”манзь тарпыд”.',
  'иисусан’ то”, сырӈа”, ня”маравы ӈамды, ембды, ӈахат ӈыхыхында ха”амвы”. ненэцие” сейдо’ хая”.',
  'хадкэвы серо манэ”мы” ненэця”',

In [2]:
def update_textgrid_with_text(textgrid_path, lines):
    tg = tgt.read_textgrid(textgrid_path, encoding="utf-8")
    tier = tg.get_tier_by_name('текст')
    if len(lines) != len([i for i in tier if i.text.strip() != ""]):
        print(f'Количество непустых интервалов в {textgrid_path} не совпадает с количеством строк: \n {len(lines)} строк, {len([i for i in tier if i.text.strip() != ""])} интервалов')
        return
    for i, interval in enumerate(tier):  #проходим по интервалам и заменяем текст на строки из txt
        if i < len(lines): 
            if interval.text.strip() == "":
                continue                #пропускаем пустые интервалы
            new_text = lines[i]         #заменяем текст интервала на соответствующую строку
            tier[i].text = new_text

    tgt.io.write_to_file(tg, textgrid_path, format="long")
    print(f"Обновлён файл: {textgrid_path}")

In [3]:
def process_all_verses(txt_path, textgrid_dir):
    verses = split_text_into_verses(txt_path)
    for verse_num, lines in verses.items():
        textgrid_path = os.path.join(textgrid_dir, f"{verse_num}.TextGrid")
        if os.path.exists(textgrid_path):
            update_textgrid_with_text(textgrid_path, lines)
        else:
            print(f"Файл не найден: {textgrid_path}")

In [7]:
mark_txt = "/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/yrk_cyrillic_Mark_new.txt"
mark_textgrid = "/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt"
process_all_verses(mark_txt, mark_textgrid)

Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/001.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/002.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/003.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/004.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/005.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/006.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/007.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/008.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/009.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/010.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/011.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/012.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/013.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/014.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/015.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt/016.TextGrid

In [8]:
john_txt = '/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John_new.txt'
john_textgrid = "/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt"
process_all_verses(john_txt, john_textgrid)

Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/001.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/002.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/003.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/004.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/005.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/006.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/007.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/008.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/009.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/010.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/011.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/012.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/013.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/014.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/015.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/016.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/017.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/018.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/019.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/020.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt/021.TextGrid

In [9]:
def pd_from_tgt(path):
    data = []
    for file in os.listdir(path):
        if file.endswith('.TextGrid'):
            tg = tgt.io.read_textgrid(os.path.join(path, file))
            tier = tg.get_tier_by_name('текст')
            for i, interval in enumerate(tier):
                    data.append({
                        "file_name" : os.path.join(path.replace('tgt', 'wav'), file.replace('TextGrid', 'wav')),
                        "start_time": interval.start_time,
                        "end_time": interval.end_time,
                        "label": interval.text,
                        "length": interval.end_time - interval.start_time
                    })
    df = pd.DataFrame(data)
    df.to_csv(path.replace(' tgt', '.csv'), index=False)
    return df

In [10]:
def calculate_time(dataframe):
    print(f'Средняя длина интервала {dataframe['length'].mean()}, максимальная {dataframe['length'].max()}, минимальная {dataframe['length'].min()}')
    print(f'Звучащее время {dataframe['length'].sum() // 3600}ч {dataframe['length'].sum() % 3600 // 60}мин {dataframe['length'].sum() % 60}с')

In [13]:
mark_df = pd_from_tgt('/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Mark/Mark old tgt')
calculate_time(mark_df)

Средняя длина интервала 2.9501555141163855, максимальная 10.686351582165756, минимальная 0.4049999999999727
Звучащее время 1.0ч 18.0мин 22.54788950151851с

In [14]:
john_df = pd_from_tgt('/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/John/John old tgt')
calculate_time(john_df)

Средняя длина интервала 4.244863884674764, максимальная 10.96875, минимальная 0.3712500000000034
Звучащее время 1.0ч 52.0мин 20.843848863525636с

In [15]:
jonah_txt = "/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah_new.txt"
jonah_textgrid = "/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah tgt"
process_all_verses(jonah_txt, jonah_textgrid)

Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah tgt/001.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah tgt/002.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah tgt/003.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/Jonah/Jonah tgt/004.TextGrid

In [16]:
jonah_df = pd_from_tgt(jonah_textgrid)
calculate_time(jonah_df)

Средняя длина интервала 5.671348998764487, максимальная 10.86459816857991, минимальная 1.1474999999999937
Звучащее время 0.0ч 7.0мин 5.351174907336542с

In [17]:
jonah_df

,file_name,start_time,end_time,label,length
0,/Users/air/Downloads/Ненецкие аудио/Библейски...,0.537219,3.540969,"амиттай’ хасава нюн’, ионан’ нум’ ерв вадам’ м...",3.003750
1,/Users/air/Downloads/Ненецкие аудио/Библейски...,4.317219,6.375969,"«юркад, сюдбя март’, ниневиян’ хань”.",2.058750
2,/Users/air/Downloads/Ненецкие аудио/Библейски...,7.050969,10.560969,"нум’ вато’ вадес”, мань няни вэва серото’ юн т...",3.510000
3,/Users/air/Downloads/Ненецкие аудио/Библейски...,11.590344,16.230969,"иона юркы”, нум’ ерв’ сякад таршишан’ хунаванз...",4.640625
4,/Users/air/Downloads/Ненецкие аудио/Библейски...,17.277219,22.643469,"таняна таршишан’ миндя ӈарка” я ӈаном’ хо, мир...",5.366250
...,...,...,...,...,...
70,/Users/air/Downloads/Ненецкие аудио/Библейски...,67.277844,73.437219,"нум’ ервэй, мань нумми, ӈопой, пыдар илми хась...",6.159375
71,/Users/air/Downloads/Ненецкие аудио/Библейски...,74.820969,84.389094,"выдара”махадни, енасяламзь мань нум’ ервм’ тен...",9.568125
72,/Users/air/Downloads/Ненецкие аудио/Библейски...,85.992219,90.362844,хусувэй” хумбанзяда сядэйха” тэяна” сянавамд х...,4.370625
73,/Users/air/Downloads/Ненецкие аудио/Библейски...,91.290969,98.597844,"маньзяван, нянд сава вади мэць, ханм’ тэвраӈгу...",7.306875
74,/Users/air/Downloads/Ненецкие аудио/Библейски...,99.981594,107.828469,илм’ ӈэдабава нум’ ерв’ ӈудахана ӈа! » нум’ е...,7.846875

In [18]:
parables_txt = '/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Gospel parables_new.txt'
parables_textgrid = '/Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Parables tgt'
process_all_verses(parables_txt, parables_textgrid)

Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Parables tgt/000.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Parables tgt/001.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Parables tgt/002.TextGrid
Обновлён файл: /Users/air/Downloads/Ненецкие аудио/Библейские ненецкие аудио/NENGP/Parables tgt/003.TextGrid

In [19]:
parables_df = pd_from_tgt(parables_textgrid)
calculate_time(parables_df)

Средняя длина интервала 6.554736949102522, максимальная 10.81687500000001, минимальная 3.3581250000000002
Звучащее время 0.0ч 8.0мин 57.48842982640679с

In [20]:
parables_df

,file_name,start_time,end_time,label,length
0,/Users/air/Downloads/Ненецкие аудио/Библейски...,0.537219,6.274719,ёховы хасава ню’ нямна ӈэда лахарё палестинаха...,5.737500
1,/Users/air/Downloads/Ненецкие аудио/Библейски...,6.983469,12.839094,"тикы мэсымана ниня ӈэди”, хэбяхасавэй ненэцие”...",5.855625
2,/Users/air/Downloads/Ненецкие аудио/Библейски...,13.446594,22.272219,"вомдартаӈгода вадидо’ пуня’ пэраць, иисус хара...",8.825625
3,/Users/air/Downloads/Ненецкие аудио/Библейски...,23.200344,30.726594,тикы хара явна ӈэда лахарёхона нисяди’ нум’ пы...,7.526250
4,/Users/air/Downloads/Ненецкие аудио/Библейски...,31.334094,36.717219,"ӈаркаюмгав, хэбяхасавэй судебада иудей” пунраб...",5.383125
...,...,...,...,...,...
77,/Users/air/Downloads/Ненецкие аудио/Библейски...,90.514719,97.787844,хаби пуня’ сало” махаданда ерваханда тикы серо...,7.273125
78,/Users/air/Downloads/Ненецкие аудио/Библейски...,98.412219,106.664094,"‹мер’ харад’ ядэлававна, харад’ помна ядэр”, м...",8.251875
79,/Users/air/Downloads/Ненецкие аудио/Библейски...,107.524719,112.739094,"хабида ма: ‹ервав, табеконд сер’ сертав, тамна...",5.214375
80,/Users/air/Downloads/Ненецкие аудио/Библейски...,113.785344,123.201594,ервада хабихинда ма: ‹мя”ни пан”ма’ е”эмня сех...,9.416250
81,/Users/air/Downloads/Ненецкие аудио/Библейски...,124.230969,130.829094,"ӈадьбя” ни нянда” мадм’, нюрте” э’ хамэхэт хан...",6.598125

In [21]:
parables_df.to_csv('parables.csv', index=False)
jonah_df.to_csv('jonah.csv', index=False)