In [1]:
import pydub
import pandas as pd
from pydub import AudioSegment
import os

In [3]:
def slice_audio(row, output_dir):
    try:
        audio = AudioSegment.from_file(row['file_name'])
        start, end = row['start_time'] * 1000, row['end_time'] * 1000
        sliced = audio[start:end]
        base_name = os.path.basename(row['file_name']).split('.')[0]
        new_file_name = f"{base_name}_{start}_{end}.wav"
        new_file_path = os.path.join(output_dir, new_file_name)
        sliced.export(new_file_path, format="wav")
        return new_file_path
    except Exception as e:
        print(f"Ошибка при обработке {row['file_name']}: {e}")
        return None

In [4]:
mark = pd.read_csv('/Users/air/Documents/PycharmProjects/Nenets/mark.csv')
john = pd.read_csv('/Users/air/Documents/PycharmProjects/Nenets/john.csv')
jonah = pd.read_csv('/Users/air/Documents/PycharmProjects/Nenets/jonah.csv')
parables = pd.read_csv('/Users/air/Documents/PycharmProjects/Nenets/parables.csv')
chumoteka = pd.read_csv('/Users/air/Downloads/Ненецкие аудио/Чумотека/Чумотека.csv')
siberian = pd.read_csv('/Users/air/Documents/PycharmProjects/Nenets/siberian.csv')
asr_dataset = pd.concat([mark, john, jonah, parables, chumoteka, siberian], ignore_index=True)

In [5]:
asr_dataset[:10]

,file_name,start_time,end_time,label,length
0,/Users/air/Downloads/Ненецкие аудио/Библейски...,3.422844,8.535969,"иисус няндо’ ма: «ненэся нянда” мадм’, тюкохон...",5.113125
1,/Users/air/Downloads/Ненецкие аудио/Библейски...,9.126594,13.834719,ханяӈы” ненэця” нум’ параӈода’ я ӈарка ныхым’ ...,4.708125
2,/Users/air/Downloads/Ненецкие аудио/Библейски...,15.606594,23.925969,"мат” яля’ ваера”махад, иисус тохоламбадахатата...",8.319375
3,/Users/air/Downloads/Ненецкие аудио/Библейски...,25.022844,33.544719,ӈаво” пирка”на сэвто’ сыртан’ пыда мирбяда ӈан...,8.521875
4,/Users/air/Downloads/Ненецкие аудио/Библейски...,34.827219,41.262711,сэв” пэсьда”. я’ сяр’ ниня хибяхарт тикахад ва...,6.435492
5,/Users/air/Downloads/Ненецкие аудио/Библейски...,42.245029,49.896594,"тикы’ пуд няндо’ илия, моисей ӈадимяха’, иисус...",7.651564
6,/Users/air/Downloads/Ненецкие аудио/Библейски...,50.487219,59.987844,"петр ӈани’ иисусан’ ма: «равви*, тюкохона мэва...",9.500625
7,/Users/air/Downloads/Ненецкие аудио/Библейски...,60.696594,70.433469,"нябиюм’ моисей’ ед’ ӈэӈгу, ӈани ӈопойхав илия’...",9.736875
8,/Users/air/Downloads/Ненецкие аудио/Библейски...,71.429094,78.010344,"ӈаво” пирка”на тир ӈадимя, сиддо’ тикы тир тид...",6.581250
9,/Users/air/Downloads/Ненецкие аудио/Библейски...,78.854094,87.139719,"«тикы мань сянда нюми, муӈганда намдорӈада”». ...",8.285625

In [6]:
#выкинем слишком короткие и слишком длинные отрезки
asr_dataset = asr_dataset[asr_dataset['length'] < 11]
asr_dataset = asr_dataset[asr_dataset['length'] > 3]
asr_dataset[:10]

,file_name,start_time,end_time,label,length
0,/Users/air/Downloads/Ненецкие аудио/Библейски...,3.422844,8.535969,"иисус няндо’ ма: «ненэся нянда” мадм’, тюкохон...",5.113125
1,/Users/air/Downloads/Ненецкие аудио/Библейски...,9.126594,13.834719,ханяӈы” ненэця” нум’ параӈода’ я ӈарка ныхым’ ...,4.708125
2,/Users/air/Downloads/Ненецкие аудио/Библейски...,15.606594,23.925969,"мат” яля’ ваера”махад, иисус тохоламбадахатата...",8.319375
3,/Users/air/Downloads/Ненецкие аудио/Библейски...,25.022844,33.544719,ӈаво” пирка”на сэвто’ сыртан’ пыда мирбяда ӈан...,8.521875
4,/Users/air/Downloads/Ненецкие аудио/Библейски...,34.827219,41.262711,сэв” пэсьда”. я’ сяр’ ниня хибяхарт тикахад ва...,6.435492
5,/Users/air/Downloads/Ненецкие аудио/Библейски...,42.245029,49.896594,"тикы’ пуд няндо’ илия, моисей ӈадимяха’, иисус...",7.651564
6,/Users/air/Downloads/Ненецкие аудио/Библейски...,50.487219,59.987844,"петр ӈани’ иисусан’ ма: «равви*, тюкохона мэва...",9.500625
7,/Users/air/Downloads/Ненецкие аудио/Библейски...,60.696594,70.433469,"нябиюм’ моисей’ ед’ ӈэӈгу, ӈани ӈопойхав илия’...",9.736875
8,/Users/air/Downloads/Ненецкие аудио/Библейски...,71.429094,78.010344,"ӈаво” пирка”на тир ӈадимя, сиддо’ тикы тир тид...",6.581250
9,/Users/air/Downloads/Ненецкие аудио/Библейски...,78.854094,87.139719,"«тикы мань сянда нюми, муӈганда намдорӈада”». ...",8.285625

In [7]:
unique_chars = sorted(list(set(asr_dataset['label'].str.cat()))) #подчистим табличку
print(unique_chars)

['\n', ' ', '!', '"', "'", '(', ')', '*', ',', '-', '.', '0', '1', '4', '5', '6', ':', ';', '?', '[', ']', 'a', '«', '»', '̈', 'Г', 'И', 'Н', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'ң', 'ӈ', '‑', '–', '’', '“', '”', '′', '‹', '›']

In [8]:
replace_table = {'ң':'ӈ', '’':"'", '“':'"', '”':'"', '′':"'", '‹':'', '›':'', '!':'', '(':'', ')':'', '*':'', ',':'',
                  '-':'', '.':'', '0':'', '1':'', '4':'', '5':'', '6':'', ':':'', ';':'', '?':'', '[':'', ']':'', 'a':'а',
                   '«':'', '»':'', '̈':'', '‑':' ', '–':'', '  ':' ', '\n':'', '   ':' '}
asr_dataset['label'] = asr_dataset['label'].str.replace(replace_table)
asr_dataset['label'] = asr_dataset['label'].str.lower()

In [9]:
after_cleanup = sorted(list(set(asr_dataset['label'].str.cat()))) #остались только буквы, тасеры и пробел
print(after_cleanup)

[' ', '"', "'", 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'ӈ']

In [10]:
asr_dataset[:10]

,file_name,start_time,end_time,label,length
0,/Users/air/Downloads/Ненецкие аудио/Библейски...,3.422844,8.535969,"иисус няндо' ма ненэся нянда"" мадм' тюкохона н...",5.113125
1,/Users/air/Downloads/Ненецкие аудио/Библейски...,9.126594,13.834719,"ханяӈы"" ненэця"" нум' параӈода' я ӈарка ныхым' ...",4.708125
2,/Users/air/Downloads/Ненецкие аудио/Библейски...,15.606594,23.925969,"мат"" яля' ваера""махад иисус тохоламбадахатата ...",8.319375
3,/Users/air/Downloads/Ненецкие аудио/Библейски...,25.022844,33.544719,"ӈаво"" пирка""на сэвто' сыртан' пыда мирбяда ӈан...",8.521875
4,/Users/air/Downloads/Ненецкие аудио/Библейски...,34.827219,41.262711,"сэв"" пэсьда"" я' сяр' ниня хибяхарт тикахад вац...",6.435492
5,/Users/air/Downloads/Ненецкие аудио/Библейски...,42.245029,49.896594,тикы' пуд няндо' илия моисей ӈадимяха' иисус' ...,7.651564
6,/Users/air/Downloads/Ненецкие аудио/Библейски...,50.487219,59.987844,"петр ӈани' иисусан' ма равви тюкохона мэвава"" ...",9.500625
7,/Users/air/Downloads/Ненецкие аудио/Библейски...,60.696594,70.433469,нябиюм' моисей' ед' ӈэӈгу ӈани ӈопойхав илия' ...,9.736875
8,/Users/air/Downloads/Ненецкие аудио/Библейски...,71.429094,78.010344,"ӈаво"" пирка""на тир ӈадимя сиддо' тикы тир тидх...",6.581250
9,/Users/air/Downloads/Ненецкие аудио/Библейски...,78.854094,87.139719,"тикы мань сянда нюми муӈганда намдорӈада"" пыдо...",8.285625

In [ ]:
output_dir = '/Users/air/Downloads/Ненецкие аудио/data'
asr_dataset['sliced_file_path'] = asr_dataset.apply(lambda row: slice_audio(row, output_dir), axis=1)
sliced_dataset = asr_dataset[['sliced_file_path', 'label']].copy()
sliced_dataset.columns = ['audio', 'transcription']
sliced_dataset.to_csv("metadata.csv", index=False)

In [12]:
sliced_dataset[:10]

,audio_file_path,text
0,/Users/air/Downloads/Ненецкие аудио/data/009_3...,"иисус няндо' ма ненэся нянда"" мадм' тюкохона н..."
1,/Users/air/Downloads/Ненецкие аудио/data/009_9...,"ханяӈы"" ненэця"" нум' параӈода' я ӈарка ныхым' ..."
2,/Users/air/Downloads/Ненецкие аудио/data/009_1...,"мат"" яля' ваера""махад иисус тохоламбадахатата ..."
3,/Users/air/Downloads/Ненецкие аудио/data/009_2...,"ӈаво"" пирка""на сэвто' сыртан' пыда мирбяда ӈан..."
4,/Users/air/Downloads/Ненецкие аудио/data/009_3...,"сэв"" пэсьда"" я' сяр' ниня хибяхарт тикахад вац..."
5,/Users/air/Downloads/Ненецкие аудио/data/009_4...,тикы' пуд няндо' илия моисей ӈадимяха' иисус' ...
6,/Users/air/Downloads/Ненецкие аудио/data/009_5...,"петр ӈани' иисусан' ма равви тюкохона мэвава"" ..."
7,/Users/air/Downloads/Ненецкие аудио/data/009_6...,нябиюм' моисей' ед' ӈэӈгу ӈани ӈопойхав илия' ...
8,/Users/air/Downloads/Ненецкие аудио/data/009_7...,"ӈаво"" пирка""на тир ӈадимя сиддо' тикы тир тидх..."
9,/Users/air/Downloads/Ненецкие аудио/data/009_7...,"тикы мань сянда нюми муӈганда намдорӈада"" пыдо..."